version: '3'
services:
  catanie:
    ports:
    - "4200:4200"
    build:
      context: catanie
  catamel:
    restart: always
    ports:
    - "3000:3000"
    build:
      context: catamel
    depends_on:
    - mongodb
  mongodb:
    image: mongo:4.1.5
  nodered:
    build:
      context: nodered
    ports:
    - "1880:1880"
