services:
  backend-next:
    image: ghcr.io/scicatproject/backend-next:v4.4.0
    depends_on:
      - mongodb
    volumes:
      - ./config/functionalAccounts.json:/home/node/app/functionalAccounts.json
    env_file:
      - ./config/.env
    labels:
      - traefik.http.routers.backend-next.rule=Host(`backend-next.localhost`)
    healthcheck:
      test: wget --spider -Y off 'http://127.0.0.1:3000/api/v3/health'
      start_period: 5s
      interval: 30s
      timeout: 10s
      retries: 5
