services:
  jupyter:
    image: quay.io/jupyter/base-notebook:x86_64-notebook-7.1.2
    depends_on:
      backend:
        condition: service_healthy
    labels:
      - traefik.http.routers.jupyter.rule=Host(`jupyter.localhost`)
      - traefik.http.services.jupyter.loadbalancer.server.port=8888
    volumes:
      - ./config/notebooks:/home/jovyan/notebooks
    env_file:
      - config/.env
    profiles:
      - analysis
